import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Sidebar from "@/ui/dashboard/sidebar/sidebar"
import styles from "@/ui/dashboard/dashboard.module.css"
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Dashboard page",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className={styles.container}>
      <div className={styles.menu}>
      <Sidebar/>
      </div>
      <div className={styles.content}>
        <div className={styles.children}>
      {children}
        </div>
      </div>
    </div>
  );
}
